/**
 * Builds a single self-contained HTML landing page from a generated kit,
 * styled with the startup's own brand colors, and triggers a download.
 * No external dependencies — everything is inline so the file works offline.
 */

function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildKitHtml(data) {
  const { strategy = {}, copy = {}, brand = {}, social = {} } = data;
  const palette = brand.palette || [];
  const dark = palette[0] || "#0F172A";
  const primary = palette[1] || "#2563EB";
  const accent = palette[2] || "#38BDF8";
  const light = palette[3] || "#F8FAFC";

  const initial = (strategy.name || "S").trim().charAt(0).toUpperCase();

  const features = (copy.features || [])
    .map(
      (f) =>
        `<div class="feature"><h3>${esc(f.title)}</h3><p>${esc(f.desc)}</p></div>`
    )
    .join("\n");

  const swatches = palette
    .map(
      (c) =>
        `<div class="sw"><span style="background:${esc(
          c
        )}"></span><code>${esc(c)}</code></div>`
    )
    .join("\n");

  const captions = (social.captions || [])
    .map((c) => `<li>${esc(c)}</li>`)
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(strategy.name || "Startup")} — landing page</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0f172a; background: ${esc(light)}; }
  .hero { background: ${esc(dark)}; color: #fff; text-align: center; padding: 90px 24px; }
  .logo { width: 64px; height: 64px; border-radius: 16px; display: inline-flex; align-items: center; justify-content: center;
          font-size: 30px; font-weight: 700; color: #fff; margin-bottom: 20px;
          background: linear-gradient(135deg, ${esc(primary)}, ${esc(accent)}); }
  .hero h1 { font-size: 44px; line-height: 1.1; margin-bottom: 14px; }
  .hero p { font-size: 18px; opacity: 0.85; max-width: 560px; margin: 0 auto; }
  .cta { display: inline-block; margin-top: 26px; background: ${esc(primary)}; color: #fff; text-decoration: none;
         padding: 14px 28px; border-radius: 10px; font-weight: 600; }
  .features { max-width: 960px; margin: 0 auto; padding: 60px 24px; display: grid; gap: 24px; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); }
  .feature { background: #fff; border: 1px solid #e2e8f0; border-radius: 14px; padding: 24px; }
  .feature h3 { color: ${esc(primary)}; margin-bottom: 8px; }
  .feature p { color: #475569; font-size: 15px; }
  .sheet { max-width: 960px; margin: 0 auto; padding: 20px 24px 70px; }
  .sheet h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; margin: 34px 0 14px; }
  .palette { display: flex; flex-wrap: wrap; gap: 14px; }
  .sw { text-align: center; font-size: 12px; color: #475569; }
  .sw span { display: block; width: 56px; height: 56px; border-radius: 10px; border: 1px solid #e2e8f0; margin-bottom: 6px; }
  ul.caps { list-style: none; display: grid; gap: 10px; }
  ul.caps li { background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 14px; font-size: 15px; color: #334155; }
  .meta { color: #64748b; font-size: 14px; }
  footer { text-align: center; padding: 30px; color: #94a3b8; font-size: 13px; }
</style>
</head>
<body>
  <section class="hero">
    <div class="logo">${esc(initial)}</div>
    <h1>${esc(copy.hero_headline || strategy.name || "")}</h1>
    <p>${esc(copy.hero_subtext || strategy.value_proposition || "")}</p>
    <a class="cta" href="#">${esc(copy.cta || "Get started")}</a>
  </section>

  <section class="features">
    ${features}
  </section>

  <section class="sheet">
    <h2>Brand</h2>
    <div class="palette">
      ${swatches}
    </div>
    <p class="meta" style="margin-top:14px;"><strong>Logo concept:</strong> ${esc(
      brand.logo_concept || ""
    )}</p>
    <p class="meta"><strong>Font:</strong> ${esc(brand.font_style || "")}</p>

    <h2>Social captions</h2>
    <ul class="caps">
      ${captions}
    </ul>
  </section>

  <footer>Generated by AI Launchpad — a crew of AI agents on AMD GPUs.</footer>
</body>
</html>`;
}

export function downloadKit(data) {
  const html = buildKitHtml(data);
  const slug =
    (data.strategy?.name || "startup")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "startup";
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slug}-kit.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
